<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy" data-toc-modified-id="Numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy</a></span><ul class="toc-item"><li><span><a href="#Data-types" data-toc-modified-id="Data-types-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Data types</a></span></li><li><span><a href="#Create-an-ndarray" data-toc-modified-id="Create-an-ndarray-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Create an ndarray</a></span></li><li><span><a href="#Type-conversion" data-toc-modified-id="Type-conversion-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Type conversion</a></span></li><li><span><a href="#Shapes,-rows,-columns" data-toc-modified-id="Shapes,-rows,-columns-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Shapes, rows, columns</a></span></li><li><span><a href="#Arithmetic" data-toc-modified-id="Arithmetic-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Arithmetic</a></span></li><li><span><a href="#Indexing-and-slicing" data-toc-modified-id="Indexing-and-slicing-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Indexing and slicing</a></span></li><li><span><a href="#Conditions" data-toc-modified-id="Conditions-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span>Conditions</a></span></li><li><span><a href="#Statistics" data-toc-modified-id="Statistics-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span>Statistics</a></span></li><li><span><a href="#Random-sampling" data-toc-modified-id="Random-sampling-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span>Random sampling</a></span></li><li><span><a href="#Sorting" data-toc-modified-id="Sorting-1.10"><span class="toc-item-num">1.10&nbsp;&nbsp;</span>Sorting</a></span></li><li><span><a href="#Matrix" data-toc-modified-id="Matrix-1.11"><span class="toc-item-num">1.11&nbsp;&nbsp;</span>Matrix</a></span><ul class="toc-item"><li><span><a href="#Multiplication" data-toc-modified-id="Multiplication-1.11.1"><span class="toc-item-num">1.11.1&nbsp;&nbsp;</span>Multiplication</a></span></li></ul></li><li><span><a href="#Comparison" data-toc-modified-id="Comparison-1.12"><span class="toc-item-num">1.12&nbsp;&nbsp;</span>Comparison</a></span></li><li><span><a href="#Unique-values" data-toc-modified-id="Unique-values-1.13"><span class="toc-item-num">1.13&nbsp;&nbsp;</span>Unique values</a></span></li><li><span><a href="#Not-a-Number" data-toc-modified-id="Not-a-Number-1.14"><span class="toc-item-num">1.14&nbsp;&nbsp;</span>Not a Number</a></span></li><li><span><a href="#File-IO" data-toc-modified-id="File-IO-1.15"><span class="toc-item-num">1.15&nbsp;&nbsp;</span>File IO</a></span></li><li><span><a href="#Additional" data-toc-modified-id="Additional-1.16"><span class="toc-item-num">1.16&nbsp;&nbsp;</span>Additional</a></span></li></ul></li></ul></div>

# Numpy

In [1]:
import numpy as np

## Data types

In [10]:
arr = np.array([1,2,3])
type(arr)

numpy.ndarray

## Create an ndarray 

In [96]:
print(np.arange(1, 10))
print(np.arange(1, 10, step=2))

[1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [97]:
print(np.linspace(0,10,11))
print(np.linspace(0,10,10, endpoint=False))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [100]:
print(np.ones(3))
print(np.ones((3,3)))

[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [101]:
print(np.zeros(3))
print(np.zeros((3,3)))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Type conversion

In [6]:
list1 = [1,2,3]
np.array(list1)

array([1, 2, 3])

In [12]:
arr = np.array([1,2,3])
arr.dtype

dtype('int32')

In [13]:
arr.astype('float')

array([1., 2., 3.])

## Shapes, rows, columns

In [16]:
arr = np.array([1,2,3,4])
arr.shape

(4,)

In [21]:
new_arr = arr.reshape(2,2)
new_arr

array([[1, 2],
       [3, 4]])

In [23]:
# by rows
new_arr.sum(axis=0)

array([4, 6])

In [22]:
# by columns
new_arr.sum(axis=1)

array([3, 7])

## Arithmetic

In [24]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr1 + arr2 # two arrays are of the same shape

array([ 6,  8, 10, 12])

In [30]:
arr1 = np.array([0,1,2]).reshape(3,1)
arr2 = np.arange(0,12).reshape(3,4)
arr3 = np.array([0,1,2,3]).reshape(1,4)

In [41]:
arr1

[0 1 2 3]


In [33]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
arr3

[[0 1 2 3]]


In [31]:
arr1 + arr2

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

In [37]:
arr1 = np.array([0,1,2,3])
arr2 = np.array([0,2,4,6])
arr1 == arr2

array([ True, False, False, False])

## Indexing and slicing

In [40]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
print(arr[2])
print(arr[2][2])

[7 8 9]
9


In [46]:
print(arr[:2][1:])
print('\n')
print(arr[:2,1:])

[[4 5 6]]


[[2 3]
 [5 6]]


In [48]:
print(arr[[0,2]]) # print the 0th and the 2nd rows

[[1 2 3]
 [7 8 9]]


## Conditions

In [50]:
x = np.array([1,2,3])
y = np.array([10,20,30])
print(np.where(x>1, x, x+2)) # if an element meet the condition, replace it with x; otherwise, replace it with y
print(np.where(x>1, x, y))

[3 2 3]
[10  2  3]


## Statistics

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr.sum()

45

In [56]:
print(arr.mean())
print(arr.mean(axis=0))
print(arr.mean(axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


## Random sampling

In [61]:
from numpy.random import default_rng

In [88]:
rng = default_rng(123) # a random number generator
arr_rd = rng.standard_normal(10)
arr_rd

array([-0.98912135, -0.36778665,  1.28792526,  0.19397442,  0.9202309 ,
        0.57710379, -0.63646365,  0.54195222, -0.31659545, -0.32238912])

Using the RandomState methods is discouraged. See https://numpy.org/doc/stable/reference/random/index.html?highlight=random#module-numpy.random

## Sorting

In [89]:
arr_rd

array([-0.98912135, -0.36778665,  1.28792526,  0.19397442,  0.9202309 ,
        0.57710379, -0.63646365,  0.54195222, -0.31659545, -0.32238912])

In [90]:
arr_rd.sort()
arr_rd

array([-0.98912135, -0.63646365, -0.36778665, -0.32238912, -0.31659545,
        0.19397442,  0.54195222,  0.57710379,  0.9202309 ,  1.28792526])

## Matrix

In [128]:
A = np.array([[1,1,1],[3,1,0],[2,1,2]])
B = np.array([[3,1,1],[2,1,3],[1,1,1]])
C = np.array([[2,0,1],[0,1,3],[1,3,1]])

In [120]:
A

array([[1, 1, 1],
       [3, 1, 0],
       [2, 1, 2]])

In [126]:
B

array([[3, 1, 1],
       [2, 1, 3],
       [1, 1, 1]])

In [129]:
C

array([[2, 0, 1],
       [0, 1, 3],
       [1, 3, 1]])

In [ ]:
np.linalg.inv(A) # get an inverse of the matrix A

### Multiplication

In [119]:
np.dot(A, B)

array([[ 6,  3,  5],
       [11,  4,  6],
       [10,  5,  7]])

In [124]:
np.matmul(A, B) # input arrays as scalars are not allowed

array([[ 6,  3,  5],
       [11,  4,  6],
       [10,  5,  7]])

In [135]:
A.dot(B)

array([[ 6,  3,  5],
       [11,  4,  6],
       [10,  5,  7]])

In [132]:
np.linalg.multi_dot([A, B, C]) # the function chains numpy.dot 
# If the first argument is 1-D it is treated as a row vector. 
# If the last argument is 1-D it is treated as a column vector. 
# The other arguments must be 2-D.

array([[17, 18, 20],
       [28, 22, 29],
       [27, 26, 32]])

In [138]:
np.dot(np.dot(A, B), C) == np.linalg.multi_dot([A, B, C])

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Comparison

In [142]:
np.array_equiv( [1, 2], [1, 2]) # true if input arrays are shape consistent and all elements equal

True

In [143]:
np.equal(1, [1,2,1,3]) # compare each element in an array with a value

array([ True, False,  True, False])

## Unique values

In [104]:
arr = np.array([0,1,1,0,2,2,3])
np.unique(arr) # equivalent to list(set(arr))

array([0, 1, 2, 3])

## Not a Number

In [144]:
a = np.nan
a

nan

In [107]:
arr = np.array([0,np.nan,2,3])
np.isnan(arr) # returns an array of boolean

array([False,  True, False, False])

## File IO

In [116]:
data = np.loadtxt("dataset.txt") # strip off spaces while loading

## Additional